# Generated by Django 3.1.8 on 2022-01-13 05:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_currency_code', models.CharField(max_length=200)),
                ('to_currency_code', models.CharField(max_length=200)),
                ('exchange_rate', models.FloatField()),
                ('last_refreshed', models.DateTimeField()),
            ],
        ),
    ]
